---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "false"
  name: nginx
  namespace: demo
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: nginx
      containers:
      - image: nginx:1.18
        name: nginx
